export const svmCaseItems = [
  {
    title: "Breast Cancer",
    case_story:
      "Breast cancer prediction has long been regarded as an important research problem in the medical and healthcare communities. This cancer develops in the breast tissue. There are several risk factors for breast cancer including female sex, obesity, lack of physical exercise, drinking alcohol, hormone replacement therapy during menopause, ionizing radiation, early age at first menstruation, having children late or not at all, and older age. There are different types of breast cancer, with different stages or spread, aggressiveness, and genetic makeup. Therefore, it would be very useful to have a system that would allow early detection and prevention which would increase the survival rates for breast cancer.",
    data_detals: "",
  },
  {
    title: "Ionosphere",
    case_story: "The ionosphere is a part of Earth’s upper atmosphere, which is ionized by solar radiation and contains a large number of free electrons. These free electrons are sufficient to affect the radio propagation and cause ionospheric delays of global navigation satellite system (GNSS) signals, which are the main sources of errors in GNSS applications. They seriously affect the performance of navigation and positioning, and must be effectively reduced or eliminated. With the development of GNSS technology and construction of ground-based GNSS stations, GNSS brings great opportunities for the development of the ionosphere research. GNSS has become one of the most important methods of ionospheric monitoring, with high accuracy, wide range, and continuous operation. Support Vector Machine (SVM) is one machine learning algorithm based on the principle of structural risk minimization and VC dimension (Vapnik Chervonenkis dimension) theory for classification, regression, and other learning tasks. SVM was first proposed by Vapnik  in 1995 and has been used in text categorization, pattern recognition, cluster analysis, etc. SVM can use training samples effectively and has great generalization ability. SVM provides a method to construct a mapping into a higher-dimensional feature space by using a kernel function, such as linear, polynomial, sigmoid, and radial basis function(RBF). At present, in the ionosphere field, the SVM algorithm is mostly used to solve the ionosphere prediction problem.",
    data_details: "",
  },
  {
    title: "Penguins",
    case_story: "With the Palmer penguins dataset, the Support Vector Machines (SVM) algorithm aims to perform a classification task. The dataset contains various physical measurements of individual penguins, such as bill length, bill depth, flipper length, and body mass, along with their corresponding species labels (Adelie, Chinstrap, and Gentoo). The problem that SVM addresses is to develop a model that can accurately classify penguins into their respective species based on the given physical measurements. The SVM algorithm finds an optimal hyperplane in the multidimensional feature space, which effectively separates the penguins of different species. This hyperplane acts as a decision boundary, allowing the SVM model to distinguish between Adelie, Chinstrap, and Gentoo penguins based on their distinct physical characteristics. By training on a subset of the dataset with labeled examples, SVM learns to create a classification model that can generalize well to unseen penguins. Once the model is trained, it can be used to predict the species of new penguins based on their physical measurements with high accuracy. The SVM classification with the Palmer penguins dataset serves as a valuable tool for researchers and conservationists to study and monitor penguin populations. It helps in understanding the distribution, population dynamics, and potential changes in the habitats of the different penguin species, which are crucial for effective wildlife management and conservation efforts.",
    data_details: "",
  },
];
